### ISSUE TITLE
postfix secrets.yaml include path doesn't include any parent-chart path

### ISSUE THREAD

**Issue by stela** [cloudposse/charts#121]
When attempting to use postfix as a subchart, its deployment.yaml appears to refer to the wrong path of the postfix secrets.yaml:
```
[debug] CHART PATH: /Users/.../myapp

Error: render error in "myapp/charts/postfix/templates/deployment.yaml": template: myapp/charts/postfix/templates/deployment.yaml:14:28: executing "myapp/charts/postfix/templates/deployment.yaml" at <include (print $.Cha...>: error calling include: template: no template "postfix/templates/secrets.yaml" associated with template "gotpl"
```

I guess the problem is that in postfix's deploy.yaml:
```yaml
     annotations:
        checksum/secret: {{ include (print $.Chart.Name "/templates/secrets.yaml") . | sha256sum }}
```
this evaluates to `postfix/templates/secrets.yaml` instead of `myapp/charts/postfix/templates/secrets.yaml`? However I tried unpacking the postfix .tgz archive and patching its contents instead of referring to it from requirements.yaml, but didn't get that working yet either.

**Comment by goruha** [comment]
@stela Absolutely right. 
That is problem of old helms.
In new versions they suggest different way to calculate sha256 code for secrets and configmaps.
I will update chart asap.

What version of helm do you use?

**Comment by stela** [comment]
Thanks @goruha!
I'm using the latest helm from homebrew at the moment (2.4.2 it seems, however see helm 2.5 was just released so will probably want to upgrade when it's in homebrew) together with minikube.

**Comment by osterman** [comment]
This should be fixed now. Let us know if it's not working for you.
