### ISSUE TITLE
[incubator/monochart] allow `monochart` to be optional

### ISSUE THREAD

**Issue by osterman** [cloudposse/charts#162]
## what
* Allow caller to disable `monochart` from appearing in release name
* Allow caller to override `monochart` release name

## why
* `monochart` in release name does not convey useful information

**Comment by alebabai** [comment]
This feature is already implemented in common chart.
https://github.com/helm/charts/tree/master/incubator/common#commonfullname
```bash
helm upgrade --install nginx incubator/monochart/ --set fullnameOverride=nginx -f incubator/monochart/values.example.yaml
```
