### ISSUE TITLE
[incubator/route53] Broken repo urls in install description.

### ISSUE THREAD

**Issue by chap-dr** [cloudposse/charts#176]
I think following lines in README.md: 
``$ helm repo add cloudposse-incubator http://charts.cloudposse.com/incubator/packages/``
``$ helm install incubator/route53-kubernetes``

Should be:
``$ helm repo add cloudposse-incubator http://charts.cloudposse.com/incubator/``
``$ helm install cloudposse-incubator/route53-kubernetes``

**Comment by osterman** [comment]
Thanks for reporting. You're correct!
